import type { RuleDef } from '../types';

/**
 * 심사 기준 카탈로그
 * - 웹접근성: KWCAG 2.2 / 평가원·문화정보서비스 통합모니터링 전문가 진단 (32+33)
 * - 웹호환성: 전자정부 웹사이트 품질관리 지침 (문화정보원 모니터링 보고서)
 * 자동 가능 항목만 axe/html-validate/커스텀으로 실검하고, 나머지는 manual(수동 확인).
 */
export const RULE_CATALOG: RuleDef[] = [
  // —— 웹접근성 (진단보고서 32항목 + 33) ——
  {
    id: 'image-alt',
    label: 'WA 1. 적절한 대체 텍스트 제공',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    autoFixable: true,
    description: '텍스트 아닌 콘텐츠에 대체 텍스트',
  },
  {
    id: 'video-caption',
    label: 'WA 2. 자막 제공',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '멀티미디어 자막·대본·수어',
  },
  {
    id: 'th-has-data-cells',
    label: 'WA 3. 표의 구성',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '표는 이해하기 쉽게 구성',
  },
  {
    id: 'wa-04-linear',
    label: 'WA 4. 콘텐츠의 선형화',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '콘텐츠는 논리적인 순서로 제공 (자동검사 제한)',
  },
  {
    id: 'wa-05-instructions',
    label: 'WA 5. 명확한 지시 사항 제공',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '지시사항은 모양·크기·위치·방향·색만으로 전달하지 않음',
  },
  {
    id: 'wa-06-color-alone',
    label: 'WA 6. 색에 무관한 콘텐츠 인식',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '색에 관계없이 인식 가능',
  },
  {
    id: 'no-autoplay-audio',
    label: 'WA 7. 자동 재생 금지',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '자동으로 소리가 재생되지 않아야 함',
  },
  {
    id: 'color-contrast',
    label: 'WA 8. 텍스트 콘텐츠의 명도 대비',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '텍스트와 배경 명도 대비',
  },
  {
    id: 'wa-09-adjacent',
    label: 'WA 9. 콘텐츠 간의 구분',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '이웃한 콘텐츠는 구별될 수 있어야 함',
  },
  {
    id: 'wa-10-keyboard',
    label: 'WA 10. 키보드 사용 보장',
    engine: 'axe-custom',
    pack: 'wa-a11y',
    enabled: true,
    description: 'DOM으로 확정 가능한 키보드·초점 문제 + 수동 확인 권유',
  },
  {
    id: 'wa-11-focus',
    label: 'WA 11. 초점 이동과 표시',
    engine: 'axe-custom',
    pack: 'wa-a11y',
    enabled: true,
    description: 'tabindex·outline 제거 등 확정 가능한 초점 문제',
  },
  {
    id: 'wa-12-target-size',
    label: 'WA 12. 조작 가능',
    engine: 'axe-custom',
    pack: 'wa-a11y',
    enabled: true,
    description: '클릭 영역 24×24(필수)·44×44(권장) CSS px',
  },
  {
    id: 'wa-13-char-key',
    label: 'WA 13. 문자단축키',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '문자 단축키 오동작 방지',
  },
  {
    id: 'meta-refresh',
    label: 'WA 14. 응답시간 조절',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '시간제한 콘텐츠 응답시간 조절 (meta-refresh 등)',
  },
  {
    id: 'wa-15-pause',
    label: 'WA 15. 정지 기능 제공',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '자동 변경 콘텐츠 움직임 제어',
  },
  {
    id: 'blink',
    label: 'WA 16. 깜빡임과 번쩍임 사용 제한',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '초당 3~50회 깜빡임·번쩍임 제한',
  },
  {
    id: 'bypass',
    label: 'WA 17. 반복 영역 건너뛰기',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '반복 영역 건너뛰기 수단',
  },
  {
    id: 'document-title',
    label: 'WA 18. 제목 제공',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '페이지·프레임·블록에 적절한 제목',
  },
  {
    id: 'page-has-heading-one',
    label: 'WA 18. 제목 제공 (h1)',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '페이지 h1 존재',
  },
  {
    id: 'link-name',
    label: 'WA 19. 적절한 링크 텍스트',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '링크 텍스트로 용도·목적 이해 가능',
  },
  {
    id: 'wa-20-fixed-ref',
    label: 'WA 20. 고정된 참조 위치 정보',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '전자출판 형식 등 고정 참조 위치',
  },
  {
    id: 'wa-21-pointer',
    label: 'WA 21. 단일 포인터 입력 지원',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '다중·경로 기반 동작은 단일 포인터로도 조작',
  },
  {
    id: 'wa-22-pointer-cancel',
    label: 'WA 22. 포인터 입력 취소',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '단일 포인터 실행 기능 취소 가능',
  },
  {
    id: 'label-content-name-mismatch',
    label: 'WA 23. 레이블과 네임',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '보이는 레이블과 접근성 이름 일치',
  },
  {
    id: 'wa-24-motion',
    label: 'WA 24. 동작기반 작동',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '동작 기반 작동(모바일 웹) 대체 수단',
  },
  {
    id: 'html-has-lang',
    label: 'WA 25. 기본 언어 표시',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '주로 사용하는 언어 명시',
  },
  {
    id: 'wa-26-user-control',
    label: 'WA 26. 사용자 요구에 따른 실행',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '의도하지 않은 기능(새 창 등) 방지·제어',
  },
  {
    id: 'wa-27-help',
    label: 'WA 27. 찾기 쉬운 도움 정보',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '도움 정보가 있으면 각 페이지에서 찾기 쉽게',
  },
  {
    id: 'wa-28-error',
    label: 'WA 28. 오류 정정',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '입력 오류 정정 방법 제공',
  },
  {
    id: 'label',
    label: 'WA 29. 레이블 제공',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '사용자 입력에 대응하는 레이블',
  },
  {
    id: 'button-name',
    label: 'WA 29. 레이블 제공 (button)',
    engine: 'axe',
    pack: 'wa-a11y',
    enabled: true,
    description: '버튼 인식 가능 이름',
  },
  {
    id: 'wa-30-auth',
    label: 'WA 30. 접근 가능한 인증',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '접근 가능한 인증(검증) 기능',
  },
  {
    id: 'wa-31-redundant-entry',
    label: 'WA 31. 반복 입력 정보',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '반복 입력 정보 자동·선택 입력',
  },
  {
    id: 'html-validate-recommended',
    label: 'WA 32. 마크업 오류 방지',
    engine: 'html-validate',
    pack: 'wa-a11y',
    enabled: true,
    description: '마크업 열고 닫음·중첩·속성 등',
  },
  {
    id: 'wa-33-webapp',
    label: 'WA 33. 웹 애플리케이션 접근성 준수',
    engine: 'manual',
    pack: 'wa-a11y',
    enabled: true,
    description: '포함된 웹 애플리케이션도 각 항목에서 점검',
  },

  // —— 웹호환성 (품질관리 지침 / 문화정보원 모니터링) ——
  {
    id: 'compat-html',
    label: '호환 1.1 (X)HTML 표준 준수',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: 'W3C Markup·HTML5 문법·중첩·속성 (전자정부 품질관리 지침)',
  },
  {
    id: 'compat-css',
    label: '호환 1.2 CSS 표준 준수',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: 'W3C CSS·시각 속성 기술표준',
  },
  {
    id: 'compat-utf8',
    label: '호환 1.3 문자(한글) 부호화 준수',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: '문자 부호화 UTF-8',
  },
  {
    id: 'compat-js',
    label: '호환 1.4 제어 기능의 표준 준수',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: 'JavaScript 오류·DOM 경고 없이 의도 동작',
  },
  {
    id: 'compat-plugin',
    label: '호환 1.5 비표준 기술 제거',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: '공공 웹사이트 플러그인 제거 가이드라인',
  },
  {
    id: 'compat-func',
    label: '호환 2.1 기능 호환성 확보',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: 'Chrome·Edge·Whale 등에서 동적 기능 동등 동작',
  },
  {
    id: 'compat-display',
    label: '호환 2.2 화면표시 호환성 확보',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: '다양한 브라우저에서 동등 표현',
  },
  {
    id: 'compat-m-func',
    label: '호환 3.1 모바일 기능 호환성 확보',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: '모바일 OS 동등 동작 (반응형/전용 없으면 감점)',
  },
  {
    id: 'compat-m-display',
    label: '호환 3.2 모바일 화면표시 호환성 확보',
    engine: 'manual',
    pack: 'wa-compat',
    enabled: true,
    description: '모바일용 화면 표시 (PC 화면만이면 감점)',
  },

  // —— 국내 관행 추가 ——
  {
    id: 'ko-blank-link-title',
    label: '새 창 열림 안내',
    engine: 'axe-custom',
    pack: 'wa-a11y',
    enabled: true,
    autoFixable: true,
    description:
      'target=_blank면 title·aria-label·숨김 텍스트 중 하나로 새창열림 안내 (WA 26 보조)',
  },
  {
    id: 'ko-linked-img-empty-alt',
    label: '컨트롤 이미지 대체 텍스트',
    engine: 'axe-custom',
    pack: 'wa-a11y',
    enabled: true,
    description:
      'a·button 등 컨트롤에 이미지만 있으면 비어 있지 않은 alt 필수. 설명 텍스트가 있으면 alt="" 허용',
  },
];
